[[redirects]]
    from = "/how-aztec-works/*"
    to = "/"

[[redirects]]
    from = "/sdk/*"
    to = "/"

[[redirects]]
    from = "/developers/*"
    to = "/"

[[redirects]]
    from = "/spec/*"
    to = "/"

[[redirects]]
    from = "/compliance"
    to = "/"